import Head from 'next/head'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Giphy Img Search</title>
        <meta name="description" content="Generated by create next app" key="home-page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Giphy Search App</h1>
    </div>
  )
}
